package io.github.devbobos.quicksell.constants

enum class PreferenceKey {
    STRING_USER_ACCESS_KEY,
    STRING_USER_ACCESS_KEY_EXPIRE_DATE,
    STRING_USER_SECRET_KEY,
    STRING_USER_SELECTED_MARKET_ID,
    STRING_USER_SELECTED_MARKET_ENGLISH_NAME,
    STRING_USER_SELECTED_MARKET_KOREAN_NAME,

    //매수
    BOOLEAN_USE_BUY_VALUE_BY_MARKET_PRICE,
    STRING_BUY_MANUAL_PRICE_VALUE,

    //매도
    BOOLEAN_USE_SELL_VALUE_BY_MARKET_PRICE,
    STRING_SELL_MANUAL_PRICE_VALUE,
    BOOLEAN_USE_BULK_SELL,

    //표시
    BOOLEAN_SHOW_BUY_BUTTON,
    BOOLEAN_SHOW_SELL_BUTTON,
    FLOAT_X_VALUE_BUY_BUTTON,
    FLOAT_Y_VALUE_BUY_BUTTON,
    FLOAT_X_VALUE_SELL_BUTTON,
    FLOAT_Y_VALUE_SELL_BUTTON,
    BOOLEAN_SHOW_TEXTVIEW_MESSAGE,
}